[theme]
base = "dark"
primaryColor = "#22d3ee"
backgroundColor = "#0a0e16"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "localhost"
